on:
  push:
    branches:
    - master

jobs:
  build_yabai:
    name: build
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v4

    - name: install zstd
      run: brew install zstd

    - name: build
      run: make archive

    - name: compress
      run: tar -cf bin.tar bin

    - name: zstd
      run: zstd bin.tar

    - name: upload build 
      uses: actions/upload-artifact@v4.0.0
      with:
        path: ./bin.tar.zst
